### ISSUE TITLE
Mission.ext. 

### ISSUE THREAD

**Issue by Alauraa** [jpwilliams/I-A-3#4]
There is a class that keeps error'ing Which is the:

class CfgWorlds
{
    class Altis: CAWorld
    {
         Description
         }
And it only crashes on that line being invalid.

**Comment by jpwilliams** [comment]
Aye that's fine. 'tis test code that should really be contained within an addon.

Will remove the CfgWorlds class next update. Thanks for the heads up! :+1:

**Comment by jpwilliams** [comment]
Removed this yonks ago.
